USE [INFO3420_12]
GO

/****** Object:  Table [dbo].[RECIPEASE_RECIPE_INGREDIENT]    Script Date: 11/21/2011 17:19:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RECIPEASE_RECIPE_INGREDIENT](
	[rec_id] [int] NOT NULL,
	[ing_name] [varchar](50) NOT NULL,
	[rec_ing_quantity] [decimal](18, 2) NULL,
	[unit_id] [int] NULL,
	[ing_sequence] [int] NULL,
 CONSTRAINT [PK_RECIPEASE_RECIPE_INGREDIENT] PRIMARY KEY CLUSTERED 
(
	[rec_id] ASC,
	[ing_name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RECIPEASE_RECIPE_INGREDIENT]  WITH CHECK ADD  CONSTRAINT [FK_RECIPEASE_RECIPE_INGREDIENT_RECIPEASE_RECIPE] FOREIGN KEY([rec_id])
REFERENCES [dbo].[RECIPEASE_RECIPE] ([rec_id])
GO

ALTER TABLE [dbo].[RECIPEASE_RECIPE_INGREDIENT] CHECK CONSTRAINT [FK_RECIPEASE_RECIPE_INGREDIENT_RECIPEASE_RECIPE]
GO

ALTER TABLE [dbo].[RECIPEASE_RECIPE_INGREDIENT]  WITH CHECK ADD  CONSTRAINT [FK_RECIPEASE_RECIPE_INGREDIENT_RECIPEASE_UNIT] FOREIGN KEY([unit_id])
REFERENCES [dbo].[RECIPEASE_UNIT] ([unit_id])
GO

ALTER TABLE [dbo].[RECIPEASE_RECIPE_INGREDIENT] CHECK CONSTRAINT [FK_RECIPEASE_RECIPE_INGREDIENT_RECIPEASE_UNIT]
GO

